Repository CorfuDB/CorfuDB, pull requests merged in 2018-11, with the labels that each got.

#1532 Cleaned Up CheckpointTest
  test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointTest.java
Labels: bug

#1534 Remove A Faulty Test
  test/src/test/java/org/corfudb/integration/WorkflowIT.java
Labels: bug

#1520 Enable Epoch Checks
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/CorfuMsgType.java
Labels: bug

#1517 Fixed Transaction Nesting Bug
  runtime/src/main/java/org/corfudb/runtime/CheckpointWriter.java
  runtime/src/main/java/org/corfudb/runtime/MultiCheckpointWriter.java
  runtime/src/main/java/org/corfudb/runtime/object/transactions/AbstractTransactionalContext.java
  runtime/src/main/java/org/corfudb/runtime/object/transactions/OptimisticTransactionalContext.java
  runtime/src/main/java/org/corfudb/runtime/object/transactions/SnapshotTransactionalContext.java
  test/src/test/java/org/corfudb/recovery/FastObjectLoaderTest.java
  test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointSmokeTest.java
  test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointTest.java
  test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointTrimTest.java
  test/src/test/java/org/corfudb/runtime/object/transactions/AbstractTransactionContextTest.java
Labels: bug

#1542 Fix StreamLogCompactionTest
  test/src/test/java/org/corfudb/infrastructure/log/StreamLogCompactionTest.java
Labels: bug

#1525 Interface for Cluster Recommendation Engine
  infrastructure/src/main/java/org/corfudb/infrastructure/management/ClusterRecommendationEngine.java
  infrastructure/src/main/java/org/corfudb/infrastructure/management/ClusterRecommendationEngineFactory.java
  infrastructure/src/main/java/org/corfudb/infrastructure/management/ClusterRecommendationStrategy.java
Labels: feature

#1540 Added An Epoch To the Transaction's Timestamp
  generator/src/main/java/org/corfudb/generator/Correctness.java
  generator/src/main/java/org/corfudb/generator/State.java
  generator/src/main/java/org/corfudb/generator/operations/CheckpointOperation.java
  generator/src/main/java/org/corfudb/generator/operations/SnapshotTxOperation.java
  infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java
  infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/workflows/AddNodeWorkflow.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/ILogData.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/IToken.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/Token.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/TokenResponse.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/TxResolutionInfo.java
  runtime/src/main/java/org/corfudb/recovery/FastObjectLoader.java
  runtime/src/main/java/org/corfudb/runtime/CheckpointWriter.java
  runtime/src/main/java/org/corfudb/runtime/MultiCheckpointWriter.java
  runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java
  runtime/src/main/java/org/corfudb/runtime/object/VersionLockedObject.java
  runtime/src/main/java/org/corfudb/runtime/object/transactions/AbstractTransactionalContext.java
  runtime/src/main/java/org/corfudb/runtime/object/transactions/OptimisticTransactionalContext.java
  runtime/src/main/java/org/corfudb/runtime/object/transactions/SnapshotTransactionalContext.java
  runtime/src/main/java/org/corfudb/runtime/object/transactions/TransactionBuilder.java
  runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
  runtime/src/main/java/org/corfudb/runtime/view/LayoutManagementView.java
  runtime/src/main/java/org/corfudb/runtime/view/ObjectsView.java
  runtime/src/main/java/org/corfudb/runtime/view/StreamsView.java
  runtime/src/main/java/org/corfudb/runtime/view/stream/BackpointerStreamView.java
  runtime/src/main/java/org/corfudb/util/Utils.java
  samples/src/main/java/org/corfudb/samples/WriteWriteTXs.java
  test/src/test/java/org/corfudb/infrastructure/SequencerServerTest.java
  test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java
  test/src/test/java/org/corfudb/integration/SealIT.java
  test/src/test/java/org/corfudb/integration/ServerRestartIT.java
  test/src/test/java/org/corfudb/integration/WorkflowIT.java
  test/src/test/java/org/corfudb/protocols/wireprotocol/TokenTest.java
  test/src/test/java/org/corfudb/recovery/FastObjectLoaderTest.java
  test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointSmokeTest.java
  test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointTest.java
  test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointTrimTest.java
  test/src/test/java/org/corfudb/runtime/clients/SequencerHandlerTest.java
  test/src/test/java/org/corfudb/runtime/object/transactions/AbstractTransactionContextTest.java
  test/src/test/java/org/corfudb/runtime/object/transactions/AbstractTransactionsTest.java
  test/src/test/java/org/corfudb/runtime/object/transactions/OptimisticTransactionContextTest.java
  test/src/test/java/org/corfudb/runtime/view/AddressSpaceViewTest.java
  test/src/test/java/org/corfudb/runtime/view/ChainReplicationViewTest.java
  test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java
  test/src/test/java/org/corfudb/runtime/view/SequencerViewTest.java
  test/src/test/java/org/corfudb/runtime/view/StreamViewTest.java
  test/src/test/java/org/corfudb/runtime/view/replication/QuorumReplicationProtocolAdditionalTests.java
Labels: bug

#1545 Correctly seal servers on epoch change
  corfu_scripts/corfu_layouts.clj
  infrastructure/src/main/java/org/corfudb/infrastructure/AbstractServer.java
  infrastructure/src/main/java/org/corfudb/infrastructure/BaseServer.java
  infrastructure/src/main/java/org/corfudb/infrastructure/BatchWriter.java
  infrastructure/src/main/java/org/corfudb/infrastructure/BatchWriterOperation.java
  infrastructure/src/main/java/org/corfudb/infrastructure/CorfuServer.java
  infrastructure/src/main/java/org/corfudb/infrastructure/IServerRouter.java
  infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
  infrastructure/src/main/java/org/corfudb/infrastructure/ManagementAgent.java
  infrastructure/src/main/java/org/corfudb/infrastructure/NettyServerRouter.java
  infrastructure/src/main/java/org/corfudb/infrastructure/ServerContext.java
  runtime/src/main/java/org/corfudb/runtime/clients/LogUnitClient.java
  runtime/src/main/java/org/corfudb/runtime/view/LayoutManagementView.java
  runtime/src/main/java/org/corfudb/runtime/view/RuntimeLayout.java
  runtime/src/main/java/org/corfudb/runtime/view/SealServersHelper.java
  test/src/test/java/org/corfudb/infrastructure/TestServerRouter.java
  test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java
  test/src/test/java/org/corfudb/integration/SealIT.java
  test/src/test/java/org/corfudb/runtime/CorfuRuntimeTest.java
  test/src/test/java/org/corfudb/runtime/view/AbstractViewTest.java
  test/src/test/java/org/corfudb/runtime/view/LayoutSealTest.java
  test/src/test/java/org/corfudb/runtime/view/LayoutViewTest.java
  test/src/test/java/org/corfudb/runtime/view/LogUnitSealTest.java
  test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java
  test/src/test/java/org/corfudb/runtime/view/replication/ChainReplicationProtocolTest.java
Labels: bug

#1556 Hole Fill RPC Bug
  infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/CorfuMsgType.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/FillHoleRequest.java
  runtime/src/main/java/org/corfudb/runtime/clients/LogUnitClient.java
  runtime/src/main/java/org/corfudb/runtime/view/replication/ChainReplicationProtocol.java
  test/src/test/java/org/corfudb/recovery/FastObjectLoaderTest.java
  test/src/test/java/org/corfudb/runtime/clients/LogUnitHandlerTest.java
Labels: bug

#1558 Prefix Trim On Token
  generator/src/main/java/org/corfudb/generator/operations/CheckpointOperation.java
  infrastructure/src/main/java/org/corfudb/infrastructure/BaseServer.java
  infrastructure/src/main/java/org/corfudb/infrastructure/BatchWriter.java
  infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
  infrastructure/src/main/java/org/corfudb/infrastructure/ServerContext.java
  infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/workflows/AddNodeWorkflow.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/TrimRequest.java
  runtime/src/main/java/org/corfudb/runtime/MultiCheckpointWriter.java
  runtime/src/main/java/org/corfudb/runtime/clients/LogUnitClient.java
  runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
  test/src/test/java/org/corfudb/infrastructure/TestServerRouter.java
  test/src/test/java/org/corfudb/integration/ServerRestartIT.java
  test/src/test/java/org/corfudb/integration/WorkflowIT.java
  test/src/test/java/org/corfudb/recovery/FastObjectLoaderTest.java
  test/src/test/java/org/corfudb/recovery/Helpers.java
  test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointSmokeTest.java
  test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointTest.java
  test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointTrimTest.java
  test/src/test/java/org/corfudb/runtime/clients/LogUnitHandlerTest.java
  test/src/test/java/org/corfudb/runtime/object/CompileProxyTest.java
  test/src/test/java/org/corfudb/runtime/object/transactions/SequencerCacheTest.java
  test/src/test/java/org/corfudb/runtime/object/transactions/StreamTest.java
  test/src/test/java/org/corfudb/runtime/view/AddressSpaceViewTest.java
  test/src/test/java/org/corfudb/runtime/view/LogUnitSealTest.java
  test/src/test/java/org/corfudb/runtime/view/StreamViewTest.java
  test/src/test/java/org/corfudb/runtime/view/ViewsGarbageCollectorTest.java
Labels: bug

#1468 Exponential back-off before address holefill.
  runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
  runtime/src/main/java/org/corfudb/runtime/exceptions/RetryExhaustedException.java
  runtime/src/main/java/org/corfudb/runtime/view/Layout.java
  runtime/src/main/java/org/corfudb/runtime/view/replication/ReadWaitHoleFillPolicy.java
  runtime/src/main/java/org/corfudb/util/retry/ExponentialBackoffRetry.java
  test/src/test/java/org/corfudb/util/retry/IRetryTest.java
Labels: bug

#1508 Sequencer Recovery Enhancement
  infrastructure/src/main/java/org/corfudb/infrastructure/BatchWriter.java
  infrastructure/src/main/java/org/corfudb/infrastructure/BatchWriterOperation.java
  infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
  infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java
  infrastructure/src/main/java/org/corfudb/infrastructure/log/InMemoryStreamLog.java
  infrastructure/src/main/java/org/corfudb/infrastructure/log/LogMetadata.java
  infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLog.java
  infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/CorfuMsgType.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/TailsResponse.java
  runtime/src/main/java/org/corfudb/recovery/FastObjectLoader.java
  runtime/src/main/java/org/corfudb/runtime/clients/LogUnitClient.java
  runtime/src/main/java/org/corfudb/runtime/clients/LogUnitHandler.java
  runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
  runtime/src/main/java/org/corfudb/runtime/view/LayoutManagementView.java
  runtime/src/main/java/org/corfudb/util/Utils.java
  test/src/test/java/org/corfudb/infrastructure/log/StreamLogFilesTest.java
  test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java
  test/src/test/java/org/corfudb/integration/WorkflowIT.java
  test/src/test/java/org/corfudb/recovery/Helpers.java
  test/src/test/java/org/corfudb/runtime/clients/LogUnitHandlerTest.java
  test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java
Labels: typ: performance
