Repository CorfuDB/CorfuDB, pull requests merged in 2018-10, with the labels that each got.

#1488 NodeRouterPool indexes routers on NodeLocator.
  runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
  runtime/src/main/java/org/corfudb/runtime/NodeRouterPool.java
  runtime/src/main/java/org/corfudb/util/NodeLocator.java
Labels: bug

#1494 Proper Singleton Implementation
  runtime/src/main/java/org/corfudb/util/concurrent/SingletonResource.java
Labels: typ: bug fix

#1491 Implemented Channel Keep-Alive
  runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
  runtime/src/main/java/org/corfudb/runtime/clients/NettyClientRouter.java
Labels: bug

#1475 Prevent memory leaks in StreamLogFiles
  infrastructure/src/main/java/org/corfudb/infrastructure/log/SegmentHandle.java
  infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
Labels: bug

#1368 Adding Null checks/Specific exceptions/Tighter visibility
  infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/workflows/AddNodeWorkflow.java
  infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/workflows/HealNodeWorkflow.java
  runtime/src/main/java/org/corfudb/runtime/view/workflows/AddNode.java
  runtime/src/main/java/org/corfudb/runtime/view/workflows/ForceRemoveNode.java
  runtime/src/main/java/org/corfudb/runtime/view/workflows/HealNode.java
  runtime/src/main/java/org/corfudb/runtime/view/workflows/RemoveNode.java
  runtime/src/main/java/org/corfudb/runtime/view/workflows/WorkflowRequest.java
Labels: bug, risk: low, typ: enhancement

#1523 Cleanup growing datastore files with a new CorfuServer option
  infrastructure/src/main/java/org/corfudb/infrastructure/CorfuServer.java
  infrastructure/src/main/java/org/corfudb/infrastructure/DataStore.java
  infrastructure/src/main/java/org/corfudb/infrastructure/ServerContext.java
  test/src/test/java/org/corfudb/infrastructure/DataStoreTest.java
  test/src/test/java/org/corfudb/infrastructure/ServerContextBuilder.java
Labels: typ: enhancement
