Repository CorfuDB/CorfuDB, pull requests merged in 2018-12, with the labels that each got.

#1577 Shutdown EventLoop Once
  runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
  runtime/src/main/java/org/corfudb/runtime/clients/NettyClientRouter.java
Labels: bug

#1578 Raw Streams Garbage Collection
  runtime/src/main/java/org/corfudb/recovery/FastObjectLoader.java
  runtime/src/main/java/org/corfudb/runtime/ViewsGarbageCollector.java
  runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java
  runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
  runtime/src/main/java/org/corfudb/runtime/view/Layout.java
  runtime/src/main/java/org/corfudb/runtime/view/StreamsView.java
  runtime/src/main/java/org/corfudb/runtime/view/stream/BackpointerStreamView.java
  runtime/src/main/java/org/corfudb/runtime/view/stream/ThreadSafeStreamView.java
  test/src/test/java/org/corfudb/runtime/view/stream/BackpointerStreamViewTest.java
Labels: bug

#1590 IStreamView:get Semantics
  runtime/src/main/java/org/corfudb/runtime/view/StreamsView.java
  test/src/test/java/org/corfudb/runtime/view/stream/BackpointerStreamViewTest.java
Labels: bug

#1599 Cleanup seq cache before setting maxConflictWildcard.
  infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java
  test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java
Labels: bug

#1594 TransactionBuilder Cleanup
  generator/src/main/java/org/corfudb/generator/State.java
  runtime/src/main/java/org/corfudb/runtime/CheckpointWriter.java
  runtime/src/main/java/org/corfudb/runtime/MultiCheckpointWriter.java
  runtime/src/main/java/org/corfudb/runtime/object/transactions/AbstractTransactionalContext.java
  runtime/src/main/java/org/corfudb/runtime/object/transactions/OptimisticTransactionalContext.java
  runtime/src/main/java/org/corfudb/runtime/object/transactions/SnapshotTransactionalContext.java
  runtime/src/main/java/org/corfudb/runtime/object/transactions/Transaction.java
  runtime/src/main/java/org/corfudb/runtime/object/transactions/TransactionBuilder.java
  runtime/src/main/java/org/corfudb/runtime/object/transactions/TransactionType.java
  runtime/src/main/java/org/corfudb/runtime/object/transactions/TransactionalContext.java
  runtime/src/main/java/org/corfudb/runtime/object/transactions/WriteAfterWriteTransactionalContext.java
  runtime/src/main/java/org/corfudb/runtime/view/ObjectsView.java
  samples/src/main/java/org/corfudb/samples/BaseCorfuAppUtils.java
  samples/src/main/java/org/corfudb/samples/WriteWriteTXs.java
  test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java
  test/src/test/java/org/corfudb/recovery/FastObjectLoaderTest.java
  test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointSmokeTest.java
  test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointTest.java
  test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointTrimTest.java
  test/src/test/java/org/corfudb/runtime/object/transactions/AbstractTransactionContextTest.java
  test/src/test/java/org/corfudb/runtime/object/transactions/AbstractTransactionsTest.java
  test/src/test/java/org/corfudb/runtime/object/transactions/SnapshotTransactionContextTest.java
Labels: typ: enhancement

#1572 Failed Authentication
  infrastructure/src/main/java/org/corfudb/infrastructure/CorfuServer.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/ClientHandshakeHandler.java
  runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
  runtime/src/main/java/org/corfudb/runtime/clients/NettyClientRouter.java
  runtime/src/main/java/org/corfudb/util/retry/ExponentialBackoffRetry.java
  runtime/src/main/java/org/corfudb/util/retry/IRetry.java
  runtime/src/main/java/org/corfudb/util/retry/IntervalRetry.java
  test/src/test/java/org/corfudb/util/retry/IRetryTest.java
Labels: bug

#1586 Set A Reasonable Timeout for Node Healing
  infrastructure/src/main/java/org/corfudb/infrastructure/ManagementServer.java
  infrastructure/src/main/java/org/corfudb/infrastructure/management/ReconfigurationEventHandler.java
Labels: bug

#1583 Fix logback.xml in testing framework
  it/src/main/resources/logback.xml
Labels: bug

#1608 LogUnitServer optimization: extract config
  infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
Labels: typ: enhancement

#1615 Aborting Large Transactions
  runtime/src/main/java/org/corfudb/runtime/exceptions/AbortCause.java
  runtime/src/main/java/org/corfudb/runtime/view/ObjectsView.java
  test/src/test/java/org/corfudb/integration/LargeWriteIT.java
  test/src/test/java/org/corfudb/integration/StreamIT.java
Labels: bug

#1624 Remove unused field and dead statements in LayoutServer
  infrastructure/src/main/java/org/corfudb/infrastructure/LayoutServer.java
Labels: risk: low, typ: enhancement

#1637 Avoid unnecessary layout updates
  infrastructure/src/main/java/org/corfudb/infrastructure/ManagementServer.java
Labels: bug

#1631 Adding more logs for failure detection
  infrastructure/src/main/java/org/corfudb/infrastructure/management/FullyConnectedClusterRecommendationEngine.java
Labels: risk: low, typ: enhancement
