Repository CorfuDB/CorfuDB, pull requests merged in 2018-05, with the labels that each got.

#1269 Persist sequencer epoch
  infrastructure/src/main/java/org/corfudb/infrastructure/ManagementAgent.java
  infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java
  infrastructure/src/main/java/org/corfudb/infrastructure/ServerContext.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/SequencerTailsRecoveryMsg.java
  runtime/src/main/java/org/corfudb/runtime/clients/SequencerClient.java
  runtime/src/main/java/org/corfudb/runtime/view/AbstractView.java
  runtime/src/main/java/org/corfudb/runtime/view/LayoutManagementView.java
  test/src/test/java/org/corfudb/infrastructure/SequencerServerTest.java
  test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java
  test/src/test/java/org/corfudb/integration/SealIT.java
  test/src/test/java/org/corfudb/runtime/clients/SequencerHandlerTest.java
  test/src/test/java/org/corfudb/runtime/view/AbstractViewTest.java
  test/src/test/java/org/corfudb/runtime/view/LayoutViewTest.java
  test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java
  test/src/test/java/org/corfudb/runtime/view/QuorumReplicationStreamViewTest.java
Labels: bug

#1267 Implements possibility of exporting corfu metrics to CSV files.
  infrastructure/src/main/java/org/corfudb/infrastructure/CorfuMsgHandler.java
  runtime/src/main/java/org/corfudb/util/MetricsUtils.java
Labels: act: in progress, feature, risk: low, typ: enhancement

#1283 Cluster status query API
  infrastructure/src/main/java/org/corfudb/infrastructure/ManagementAgent.java
  infrastructure/src/main/java/org/corfudb/infrastructure/ManagementServer.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/NetworkMetrics.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/NodeView.java
  runtime/src/main/java/org/corfudb/runtime/view/ClusterStatusReport.java
  runtime/src/main/java/org/corfudb/runtime/view/Layout.java
  runtime/src/main/java/org/corfudb/runtime/view/ManagementView.java
  test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java
Labels: feature

#1282 Implement round trip timing of Corfu Messages from client
  runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
  runtime/src/main/java/org/corfudb/runtime/clients/ClientMsgHandler.java
  runtime/src/main/java/org/corfudb/runtime/clients/LogUnitClient.java
  runtime/src/main/java/org/corfudb/runtime/clients/NettyClientRouter.java
  runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java
  runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
  runtime/src/main/java/org/corfudb/util/CorfuComponent.java
  runtime/src/main/java/org/corfudb/util/MetricsUtils.java
  test/src/test/java/org/corfudb/runtime/clients/TestClientRouter.java
Labels: act: in progress, feature, risk: low, typ: enhancement

#1290 Enabling multi indexing
  generator/src/main/java/org/corfudb/generator/StringIndexer.java
  runtime/src/main/java/org/corfudb/runtime/collections/CorfuTable.java
  test/src/test/java/org/corfudb/integration/ServerRestartIT.java
  test/src/test/java/org/corfudb/runtime/collections/CorfuTableTest.java
  test/src/test/java/org/corfudb/runtime/collections/StringIndexer.java
  test/src/test/java/org/corfudb/runtime/collections/StringMultiIndexer.java
Labels: act: ready, feature, typ: enhancement
