Repository CorfuDB/CorfuDB, pull requests merged in 2018-06, with the labels that each got.

#1326 Chain min replication factor set to 1.
  runtime/src/main/java/org/corfudb/runtime/view/Layout.java
  runtime/src/main/java/org/corfudb/runtime/view/LayoutBuilder.java
  test/src/test/java/org/corfudb/infrastructure/LayoutBuilderTest.java
  test/src/test/java/org/corfudb/runtime/view/LayoutManagementViewTest.java
  test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java
Labels: bug

#1328 Using named generic instead of wildcard generic of Comparable for IndexRegistry
  runtime/src/main/java/org/corfudb/runtime/collections/CorfuTable.java
Labels: act: ready

#1301 Refactoring: emptying handler's queues and using singleton instead of list
  infrastructure/src/main/java/org/corfudb/infrastructure/ServerHandshakeHandler.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/ClientHandshakeHandler.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/MultipleReadRequest.java
Labels: act: ready, act: wait to merge, typ: enhancement, typ: refactoring

#1331 Copy layout on daatastore access
  infrastructure/src/main/java/org/corfudb/infrastructure/LayoutServer.java
  infrastructure/src/main/java/org/corfudb/infrastructure/ManagementAgent.java
  infrastructure/src/main/java/org/corfudb/infrastructure/ManagementServer.java
  infrastructure/src/main/java/org/corfudb/infrastructure/ServerContext.java
Labels: bug

#1310 Adding JVM and troubleshooting metrics
  infrastructure/pom.xml
  runtime/pom.xml
  runtime/src/main/java/org/corfudb/util/MetricsUtils.java
Labels: act: ready, feature, risk: low, typ: enhancement

#1313 Simplifying adding metrics context to handlers on CorfuMsgHandler
  infrastructure/src/main/java/org/corfudb/infrastructure/CorfuMsgHandler.java
  runtime/src/main/java/org/corfudb/runtime/clients/LogUnitClient.java
  runtime/src/main/java/org/corfudb/runtime/clients/NettyClientRouter.java
  runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java
  runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
  runtime/src/main/java/org/corfudb/util/CorfuComponent.java
  test/src/test/java/org/corfudb/runtime/clients/TestClientRouter.java
Labels: act: ready, risk: low, typ: enhancement
