Repository CorfuDB/CorfuDB, pull requests merged in 2018-07, with the labels that each got.

#1346 Fix Binding Bug and Enable Virtual Interface Binding
  runtime/src/main/java/org/corfudb/util/NetworkUtils.java
Labels: typ: bug fix

#1342 Select responsive failover sequencer.
  runtime/src/main/java/org/corfudb/runtime/view/LayoutBuilder.java
  test/src/test/java/org/corfudb/infrastructure/LayoutBuilderTest.java
Labels: bug

#1355 Removing logback analyzer
  infrastructure/pom.xml
  runtime/pom.xml
  runtime/src/main/java/org/corfudb/util/MetricsUtils.java
Labels: risk: low

#1361 Surface Timeout Exceptions
  runtime/src/main/java/org/corfudb/runtime/clients/ManagementClient.java
  runtime/src/main/java/org/corfudb/runtime/view/workflows/AddNode.java
  runtime/src/main/java/org/corfudb/runtime/view/workflows/ForceRemoveNode.java
  runtime/src/main/java/org/corfudb/runtime/view/workflows/HealNode.java
  runtime/src/main/java/org/corfudb/runtime/view/workflows/RemoveNode.java
  runtime/src/main/java/org/corfudb/runtime/view/workflows/WorkflowRequest.java
Labels: typ: bug fix

#1367 Prevent Incorrect Nesting
  runtime/src/main/java/org/corfudb/runtime/object/transactions/TransactionalContext.java
  test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointSmokeTest.java
  test/src/test/java/org/corfudb/runtime/view/ObjectsViewTest.java
Labels: typ: bug fix

#1378 Initialize Router Epoch
  infrastructure/src/main/java/org/corfudb/infrastructure/ManagementAgent.java
  infrastructure/src/main/java/org/corfudb/infrastructure/NettyServerRouter.java
Labels: bug

#1376 RPC Failure On Unavailable Servers
  infrastructure/src/main/java/org/corfudb/infrastructure/CorfuMsgHandler.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/CorfuMsgType.java
  runtime/src/main/java/org/corfudb/runtime/clients/BaseHandler.java
  runtime/src/main/java/org/corfudb/runtime/exceptions/UnavailableServerException.java
  runtime/src/main/java/org/corfudb/runtime/view/AbstractView.java
  test/src/test/java/org/corfudb/infrastructure/BaseServerTest.java
Labels: bug

#1388 Use Native Implementation for SSL
  pom.xml
  runtime/src/main/java/org/corfudb/security/tls/SslContextConstructor.java
Labels: typ: performance

#1387 Ignore already bootstrapped nodes if BootstrapUtil retried.
  infrastructure/src/main/java/org/corfudb/infrastructure/ManagementServer.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/CorfuMsgType.java
  runtime/src/main/java/org/corfudb/runtime/BootstrapUtil.java
  runtime/src/main/java/org/corfudb/runtime/clients/ManagementClient.java
  test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java
Labels: bug

#1385 Force remove bug
  runtime/src/main/java/org/corfudb/runtime/view/workflows/AddNode.java
  runtime/src/main/java/org/corfudb/runtime/view/workflows/ForceRemoveNode.java
  runtime/src/main/java/org/corfudb/runtime/view/workflows/HealNode.java
  runtime/src/main/java/org/corfudb/runtime/view/workflows/RemoveNode.java
  runtime/src/main/java/org/corfudb/runtime/view/workflows/WorkflowRequest.java
  test/src/test/java/org/corfudb/integration/AbstractIT.java
  test/src/test/java/org/corfudb/integration/Harness.java
  test/src/test/java/org/corfudb/integration/WorkflowIT.java
Labels: bug

#1396 Transfer trimMark on stateTransfer.
  infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/workflows/AddNodeWorkflow.java
  test/src/test/java/org/corfudb/integration/Harness.java
  test/src/test/java/org/corfudb/integration/WorkflowIT.java
  test/src/test/java/org/corfudb/integration/cluster/Harness/Node.java
Labels: bug

#1400 Timer Race
  runtime/src/main/java/org/corfudb/runtime/clients/NettyClientRouter.java
Labels: bug

#1403 Handle UnavailableServerException on CorfuRuntime
  runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
Labels: bug
