Repository CorfuDB/CorfuDB, pull requests merged in 2018-03, with the labels that each got.

#1215 ArithmeticException Fix
  runtime/src/main/java/org/corfudb/runtime/view/workflows/WorkflowRequest.java
  test/src/test/java/org/corfudb/integration/WorkflowIT.java
Labels: bug

#1212 Added Integrity Checks
  infrastructure/src/main/java/org/corfudb/infrastructure/DataStore.java
  test/src/test/java/org/corfudb/infrastructure/DataStoreTest.java
Labels: bug

#1211 StackOverflow Fix
  runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java
  test/src/test/java/org/corfudb/runtime/object/CompileProxyTest.java
Labels: bug

#1214 Set Max Write Limit
  runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
  runtime/src/main/java/org/corfudb/runtime/clients/LogUnitClient.java
  runtime/src/main/java/org/corfudb/runtime/exceptions/WriteSizeException.java
  runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
  runtime/src/main/java/org/corfudb/runtime/view/RuntimeLayout.java
  test/src/test/java/org/corfudb/integration/StreamIT.java
Labels: feature

#1229 Fix object creation performance regression #1192
  runtime/src/main/java/org/corfudb/runtime/view/AbstractView.java
  runtime/src/main/java/org/corfudb/runtime/view/RuntimeLayout.java
Labels: Performance Testing

#1245 Reporting Corfu metrics to MBeans
  runtime/src/main/java/org/corfudb/util/MetricsUtils.java
Labels: act: in progress, feature
