Repository CorfuDB/CorfuDB, pull requests merged in 2018-08, with the labels that each got.

#1401 Transaction Abort Exception Cause for slow writers
  infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
  infrastructure/src/main/java/org/corfudb/infrastructure/log/InMemoryStreamLog.java
  infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLog.java
  infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
  infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogWithRankedAddressSpace.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/CorfuMsgType.java
  runtime/src/main/java/org/corfudb/runtime/clients/LogUnitHandler.java
  runtime/src/main/java/org/corfudb/runtime/exceptions/AbortCause.java
  runtime/src/main/java/org/corfudb/runtime/exceptions/OverwriteCause.java
  runtime/src/main/java/org/corfudb/runtime/exceptions/OverwriteException.java
  runtime/src/main/java/org/corfudb/runtime/object/transactions/OptimisticTransactionalContext.java
  runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
  runtime/src/main/java/org/corfudb/runtime/view/replication/QuorumReplicationProtocol.java
  test/src/test/java/org/corfudb/runtime/clients/LogUnitHandlerTest.java
  test/src/test/java/org/corfudb/runtime/object/transactions/OptimisticTransactionContextTest.java
Labels: bug

#1414 Force Timeout On Connection
  runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
  runtime/src/main/java/org/corfudb/runtime/clients/NettyClientRouter.java
Labels: bug

#1438 Configurable Transfer Batch Size
  infrastructure/src/main/java/org/corfudb/infrastructure/CorfuServer.java
  infrastructure/src/main/java/org/corfudb/infrastructure/ServerContext.java
  infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/workflows/AddNodeWorkflow.java
  test/src/test/java/org/corfudb/infrastructure/ServerContextBuilder.java
Labels: bug

#1441 Reject empty seq bootstrap msg on failover.
  infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/SequencerTailsRecoveryMsg.java
  test/src/test/java/org/corfudb/infrastructure/SequencerServerTest.java
  test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java
Labels: bug, priority: high

#1436 Rethrow systemDownHandler exceptions
  runtime/src/main/java/org/corfudb/runtime/view/AbstractView.java
Labels: bug

#1445 Fix singleton resource locking.
  runtime/src/main/java/org/corfudb/util/concurrent/SingletonResource.java
Labels: bug

#1453 Removing redundant jobs from travis.
  .travis.yml
  .travis_scripts/mvnrepo.sh
  .travis_scripts/push_deb.sh
  .travis_scripts/push_docker.sh
Labels: non-code, risk: low

#1457 Learn trim mark and trim resolvedQueue.
  runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
  runtime/src/main/java/org/corfudb/runtime/clients/LogUnitClient.java
  runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
  runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractQueuedStreamView.java
  test/src/test/java/org/corfudb/runtime/view/AddressSpaceViewTest.java
Labels: bug

#1458 Learn trim mark and trim resolvedQueue.
  runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
  runtime/src/main/java/org/corfudb/runtime/clients/LogUnitClient.java
  runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
  runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractQueuedStreamView.java
  test/src/test/java/org/corfudb/runtime/view/AddressSpaceViewTest.java
Labels: bug

#1308 Adding ability to filter inbound messages at Netty Client Router
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/CorfuMsgType.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/InboundMsgFilterHandler.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/MsgHandlingFilter.java
  runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
  runtime/src/main/java/org/corfudb/runtime/clients/NettyClientRouter.java
  test/src/test/java/org/corfudb/integration/CorfuMsgFilterIT.java
  test/src/test/java/org/corfudb/runtime/clients/NettyCommTest.java
Labels: act: ready, feature

#1352 Avoiding unnecessary copying of servers during server removals
  runtime/src/main/java/org/corfudb/runtime/view/LayoutBuilder.java
  test/src/test/java/org/corfudb/infrastructure/LayoutBuilderTest.java
Labels: act: ready, act: wait to merge, typ: enhancement

#1377 Ability to measure and collect memory consumptions metrics of corfu objects
  runtime/pom.xml
  runtime/src/main/java/org/corfudb/util/MetricsUtils.java
  test/src/test/java/org/corfudb/integration/AbstractIT.java
  test/src/test/java/org/corfudb/integration/MemoryFootprintIT.java
  test/src/test/java/org/corfudb/util/MemoryFootprintMeasurerIT.java
Labels: act: ready, feature, typ: enhancement
