Repository CorfuDB/CorfuDB, pull requests merged in 2019-06, with the labels that each got.

#1924 Make MemoryFootprintIT more reliable by forcing GC first
  test/src/test/java/org/corfudb/integration/MemoryFootprintIT.java
Labels: bug

#1925 Flush Write Buffer
  infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
Labels: bug

#1923 Log Unit Trim Mark Rebuilt Fix
  infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
  infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java
  infrastructure/src/main/java/org/corfudb/infrastructure/log/InMemoryStreamLog.java
  infrastructure/src/main/java/org/corfudb/infrastructure/log/LogMetadata.java
  infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
  runtime/src/main/java/org/corfudb/runtime/view/stream/StreamAddressSpace.java
  test/src/test/java/org/corfudb/infrastructure/LogUnitServerTest.java
  test/src/test/java/org/corfudb/runtime/clients/LogUnitHandlerTest.java
Labels: bug

#1920 Make ping epoch unaware.
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/CorfuMsgType.java
  test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java
  test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java
Labels: 0.2.3, 0.3.0, bug

#1918 Transfer delta in state transfer.
  infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
  infrastructure/src/main/java/org/corfudb/infrastructure/log/InMemoryStreamLog.java
  infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLog.java
  infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
  infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/RestoreRedundancyMergeSegments.java
  infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java
  infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/workflows/AddNodeWorkflow.java
  infrastructure/src/test/java/org/corfudb/infrastructure/management/PollReportTest.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/CorfuMsgType.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/KnownAddressRequest.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/KnownAddressResponse.java
  runtime/src/main/java/org/corfudb/runtime/clients/LogUnitClient.java
  runtime/src/main/java/org/corfudb/runtime/clients/LogUnitHandler.java
  test/src/test/java/org/corfudb/runtime/view/AbstractViewTest.java
  test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java
  test/src/test/java/org/corfudb/runtime/view/StateTransferTest.java
  test/src/test/java/org/corfudb/test/TestUtils.java
Labels: 0.2.3, 0.3.0, bug

#1936 Set Default SSL provider
  runtime/src/main/java/org/corfudb/security/tls/SslContextConstructor.java
Labels: bug

#1938 Fix test - verifyPartialStateTransferCompletionOnRetry.
  test/src/test/java/org/corfudb/runtime/view/StateTransferTest.java
Labels: 0.2.3, 0.3.0

#1919 Shutdown stale CorfuRuntimes in ITs.
  test/src/test/java/org/corfudb/integration/AbstractIT.java
  test/src/test/java/org/corfudb/integration/MemoryFootprintIT.java
  test/src/test/java/org/corfudb/integration/SecurityIT.java
  test/src/test/java/org/corfudb/integration/ServerRestartIT.java
  test/src/test/java/org/corfudb/integration/StreamAddressDiscoveryIT.java
  test/src/test/java/org/corfudb/integration/TransactionStreamIT.java
  test/src/test/java/org/corfudb/util/MemoryFootprintMeasurerIT.java
Labels: 0.2.3, 0.3.0

#1901 Introducing non-cacheable reads on log unit server.
  infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
  infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServerCache.java
  infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/ILogData.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/MultipleReadRequest.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/ReadRequest.java
  runtime/src/main/java/org/corfudb/recovery/FastObjectLoader.java
  runtime/src/main/java/org/corfudb/runtime/clients/LogUnitClient.java
  runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
  runtime/src/main/java/org/corfudb/runtime/view/replication/ChainReplicationProtocol.java
  runtime/src/main/java/org/corfudb/runtime/view/replication/IReplicationProtocol.java
  runtime/src/main/java/org/corfudb/runtime/view/replication/QuorumReplicationProtocol.java
  runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractQueuedStreamView.java
  test/src/test/java/org/corfudb/infrastructure/LogUnitCacheTest.java
  test/src/test/java/org/corfudb/infrastructure/LogUnitServerAssertions.java
  test/src/test/java/org/corfudb/infrastructure/LogUnitServerTest.java
  test/src/test/java/org/corfudb/runtime/clients/LogUnitHandlerTest.java
Labels: typ: performance

#1947 Retry getStreamAddressSpace if disconnected from cluster.
  runtime/src/main/java/org/corfudb/runtime/view/SequencerView.java
  test/src/test/java/org/corfudb/runtime/view/AbstractViewTest.java
  test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java
  test/src/test/java/org/corfudb/runtime/view/SequencerViewTest.java
Labels: 0.2.3, 0.3.0, bug

#1948 Retry getStreamAddressSpace if disconnected from cluster.
  runtime/src/main/java/org/corfudb/runtime/view/SequencerView.java
  test/src/test/java/org/corfudb/runtime/view/AbstractViewTest.java
  test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java
  test/src/test/java/org/corfudb/runtime/view/SequencerViewTest.java
Labels: bug

#1946 Bug Fix Stream Layer Ignore Trimmed Exceptions
  runtime/src/main/java/org/corfudb/runtime/exceptions/TrimmedException.java
  runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
  runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractQueuedStreamView.java
  runtime/src/main/java/org/corfudb/runtime/view/stream/AddressMapStreamView.java
  runtime/src/main/java/org/corfudb/runtime/view/stream/BackpointerStreamView.java
  test/src/test/java/org/corfudb/runtime/view/AbstractViewTest.java
  test/src/test/java/org/corfudb/runtime/view/stream/AbstractStreamViewTest.java
  test/src/test/java/org/corfudb/runtime/view/stream/AddressMapStreamViewTest.java
  test/src/test/java/org/corfudb/runtime/view/stream/BackpointerStreamViewTest.java
Labels: typ: bug fix

#1945 StreamLogFile fixes and improvements.
  infrastructure/src/main/java/org/corfudb/infrastructure/log/LogMetadata.java
  infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
  test/src/test/java/org/corfudb/infrastructure/LogUnitCacheTest.java
  test/src/test/java/org/corfudb/infrastructure/log/StreamLogFilesTest.java
Labels: defect

#1970 Unify Fill Hole Write Path
  infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/CorfuMsgType.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/FillHoleRequest.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/LogData.java
  runtime/src/main/java/org/corfudb/runtime/clients/LogUnitClient.java
  runtime/src/main/java/org/corfudb/runtime/view/replication/ChainReplicationProtocol.java
  test/src/test/java/org/corfudb/integration/StreamAddressDiscoveryIT.java
  test/src/test/java/org/corfudb/recovery/FastObjectLoaderTest.java
  test/src/test/java/org/corfudb/runtime/clients/LogUnitHandlerTest.java
Labels: typ: enhancement, typ: refactoring
