Repository CorfuDB/CorfuDB, pull requests merged in 2019-08, with the labels that each got.

#2013 Cache Concurrency
  runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
  runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
Labels: typ: enhancement

#2081 State Transfer Stream Address Space Bug Fix
  infrastructure/src/main/java/org/corfudb/infrastructure/log/LogMetadata.java
  test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java
Labels: bug

#2083 Fix Netty channel keep alive NPE.
  runtime/src/main/java/org/corfudb/runtime/clients/NettyClientRouter.java
Labels: bug, typ: bug fix

#2089 [Corfu-0.2.3] Porting: Fix Netty channel keep alive NPE
  runtime/src/main/java/org/corfudb/runtime/clients/NettyClientRouter.java
Labels: bug, typ: bug fix

#2090 ILogData: Get rid of backward dependency on LogEntry.
  runtime/src/main/java/org/corfudb/protocols/logprotocol/LogEntry.java
  runtime/src/main/java/org/corfudb/protocols/logprotocol/MultiObjectSMREntry.java
  runtime/src/main/java/org/corfudb/protocols/logprotocol/MultiSMREntry.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/ILogData.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/IMetadata.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/LogData.java
  runtime/src/main/java/org/corfudb/recovery/FastObjectLoader.java
  runtime/src/main/java/org/corfudb/runtime/object/StreamViewSMRAdapter.java
  runtime/src/main/java/org/corfudb/runtime/object/VersionLockedObject.java
Labels: defect, typ: refactoring

#2099 Correct CheckpointWriter return Token
  infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/TokenResponse.java
  runtime/src/main/java/org/corfudb/runtime/CheckpointWriter.java
  runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
  runtime/src/main/java/org/corfudb/runtime/MultiCheckpointWriter.java
  runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java
  runtime/src/main/java/org/corfudb/runtime/view/SequencerView.java
  runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractQueuedStreamView.java
  test/src/test/java/org/corfudb/infrastructure/SequencerServerTest.java
  test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java
  test/src/test/java/org/corfudb/integration/CmdletIT.java
  test/src/test/java/org/corfudb/integration/ServerRestartIT.java
  test/src/test/java/org/corfudb/integration/StreamAddressDiscoveryIT.java
  test/src/test/java/org/corfudb/recovery/FastObjectLoaderTest.java
  test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointSmokeTest.java
  test/src/test/java/org/corfudb/runtime/clients/SequencerHandlerTest.java
  test/src/test/java/org/corfudb/runtime/object/transactions/OptimisticTransactionContextTest.java
  test/src/test/java/org/corfudb/runtime/view/AbstractViewTest.java
  test/src/test/java/org/corfudb/runtime/view/LayoutViewTest.java
  test/src/test/java/org/corfudb/runtime/view/SequencerViewTest.java
  test/src/test/java/org/corfudb/runtime/view/StateTransferTest.java
  test/src/test/java/org/corfudb/runtime/view/StreamViewTest.java
Labels: bug

#2100 [0.2.3] Correct CheckpointWriter return Token
  infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/TokenResponse.java
  runtime/src/main/java/org/corfudb/runtime/CheckpointWriter.java
  runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
  runtime/src/main/java/org/corfudb/runtime/MultiCheckpointWriter.java
  runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java
  runtime/src/main/java/org/corfudb/runtime/view/SequencerView.java
  runtime/src/main/java/org/corfudb/runtime/view/StreamsView.java
  runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractQueuedStreamView.java
  test/src/test/java/org/corfudb/infrastructure/SequencerServerTest.java
  test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java
  test/src/test/java/org/corfudb/integration/CmdletIT.java
  test/src/test/java/org/corfudb/integration/ServerRestartIT.java
  test/src/test/java/org/corfudb/integration/StreamAddressDiscoveryIT.java
  test/src/test/java/org/corfudb/recovery/FastObjectLoaderTest.java
  test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointSmokeTest.java
  test/src/test/java/org/corfudb/runtime/clients/SequencerHandlerTest.java
  test/src/test/java/org/corfudb/runtime/object/transactions/OptimisticTransactionContextTest.java
  test/src/test/java/org/corfudb/runtime/view/AbstractViewTest.java
  test/src/test/java/org/corfudb/runtime/view/LayoutViewTest.java
  test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java
  test/src/test/java/org/corfudb/runtime/view/SequencerViewTest.java
  test/src/test/java/org/corfudb/runtime/view/StateTransferTest.java
  test/src/test/java/org/corfudb/runtime/view/StreamViewTest.java
Labels: 0.2.3
