Repository CorfuDB/CorfuDB, pull requests merged in 2019-04, with the labels that each got.

#1805 Cache Race Fix
  infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java
  runtime/src/main/java/org/corfudb/recovery/RecoveryUtils.java
  runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
  runtime/src/main/java/org/corfudb/runtime/view/replication/ChainReplicationProtocol.java
  runtime/src/main/java/org/corfudb/runtime/view/replication/IReplicationProtocol.java
  runtime/src/main/java/org/corfudb/runtime/view/replication/QuorumReplicationProtocol.java
  test/src/test/java/org/corfudb/recovery/FastObjectLoaderTest.java
  test/src/test/java/org/corfudb/runtime/view/AddressSpaceViewTest.java
Labels: bug

#1793 Remove unused exceptions and dead code
  migration/pom.xml
  migration/proto/types.proto
  migration/src/main/java/org/corfudb/migration/EndpointMigration.java
  migration/src/main/java/org/corfudb/migration/LayoutReset.java
  migration/src/main/java/org/corfudb/migration/LogFormat1to2.java
  pom.xml
  runtime/src/main/java/org/corfudb/runtime/ViewsGarbageCollector.java
  runtime/src/main/java/org/corfudb/runtime/exceptions/GarbageCollectorException.java
  runtime/src/main/java/org/corfudb/runtime/exceptions/ObjectExistsException.java
  runtime/src/main/java/org/corfudb/runtime/exceptions/SequencerRejectedException.java
  runtime/src/main/java/org/corfudb/runtime/exceptions/UnprocessedException.java
  test/src/test/java/org/corfudb/runtime/collections/FGMapTest.java
Labels: typ: refactoring

#1843 Add new reboot utilty to prevent router race, fix netty channel leak.
  it/src/main/java/org/corfudb/universe/group/cluster/CorfuClusterParams.java
  it/src/main/java/org/corfudb/universe/group/cluster/docker/DockerCorfuCluster.java
  it/src/main/java/org/corfudb/universe/group/cluster/vm/VmCorfuCluster.java
  runtime/src/main/java/org/corfudb/runtime/BootstrapUtil.java
  runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
  runtime/src/main/java/org/corfudb/runtime/RebootUtil.java
  runtime/src/main/java/org/corfudb/runtime/clients/BaseHandler.java
  runtime/src/main/java/org/corfudb/runtime/clients/NettyClientRouter.java
  runtime/src/main/java/org/corfudb/runtime/exceptions/ShutdownException.java
  test/src/test/java/org/corfudb/integration/AbstractIT.java
  test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java
Labels: typ: bug fix
