Repository CorfuDB/CorfuDB, pull requests merged in 2019-07, with the labels that each got.

#1993 RemoveNode: prevent unresponsive node elected as new primary sequencer.
  runtime/src/main/java/org/corfudb/runtime/view/LayoutManagementView.java
  test/src/test/java/org/corfudb/runtime/view/LayoutManagementViewTest.java
Labels: 0.2.3, bug

#1998 [Corfu-0.2.3] RemoveNode: prevent unresponsive node elected as new primary sequencer.
  runtime/src/main/java/org/corfudb/runtime/view/LayoutManagementView.java
  test/src/test/java/org/corfudb/runtime/view/LayoutManagementViewTest.java
Labels: 0.2.3, bug

#2001 [Corfu_0.2.3] Log Unit Stream's Address Space rebuilt
  infrastructure/src/main/java/org/corfudb/infrastructure/BatchProcessor.java
  infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java
  infrastructure/src/main/java/org/corfudb/infrastructure/log/InMemoryStreamLog.java
  infrastructure/src/main/java/org/corfudb/infrastructure/log/LogMetadata.java
  infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
  runtime/src/main/java/org/corfudb/runtime/view/stream/StreamAddressSpace.java
  test/src/test/java/org/corfudb/integration/ServerRestartIT.java
  test/src/test/java/org/corfudb/integration/StreamAddressDiscoveryIT.java
  test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointSmokeTest.java
Labels: 0.2.3

#2008 Convert Recursion to Iteration
  runtime/src/main/java/org/corfudb/runtime/view/stream/AddressMapStreamView.java
  runtime/src/main/java/org/corfudb/runtime/view/stream/BackpointerStreamView.java
Labels: 0.2.3

#1974 Add Priority Level For Clients
  infrastructure/src/main/java/org/corfudb/infrastructure/BatchProcessor.java
  infrastructure/src/main/java/org/corfudb/infrastructure/CorfuServer.java
  infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
  infrastructure/src/main/java/org/corfudb/infrastructure/ManagementServer.java
  infrastructure/src/main/java/org/corfudb/infrastructure/ResourceQuota.java
  infrastructure/src/main/java/org/corfudb/infrastructure/ServerContext.java
  infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLog.java
  infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
  infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/Orchestrator.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/ClientHandshakeHandler.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/CorfuMsg.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/ICorfuPayload.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/IMetadata.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/LogData.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/PriorityLevel.java
  runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
  runtime/src/main/java/org/corfudb/runtime/clients/AbstractClient.java
  runtime/src/main/java/org/corfudb/runtime/clients/IClient.java
  runtime/src/main/java/org/corfudb/runtime/exceptions/AbortCause.java
  runtime/src/main/java/org/corfudb/runtime/exceptions/QuotaExceededException.java
  runtime/src/main/java/org/corfudb/runtime/object/transactions/OptimisticTransactionalContext.java
  runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
  runtime/src/main/java/org/corfudb/runtime/view/ObjectsView.java
  runtime/src/main/java/org/corfudb/runtime/view/RuntimeLayout.java
  test/src/test/java/org/corfudb/infrastructure/LogUnitServerTest.java
  test/src/test/java/org/corfudb/infrastructure/ResourceQuotaTest.java
  test/src/test/java/org/corfudb/infrastructure/ServerContextBuilder.java
  test/src/test/java/org/corfudb/infrastructure/log/StreamLogFilesTest.java
  test/src/test/java/org/corfudb/integration/AbstractIT.java
  test/src/test/java/org/corfudb/integration/LogSizeQuotaIT.java
  test/src/test/java/org/corfudb/runtime/clients/LogUnitHandlerTest.java
  test/src/test/java/org/corfudb/runtime/view/replication/QuorumReplicationProtocolTest.java
Labels: 0.2.3, feature

#1981 Memory Size Based Eviction
  runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
  runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
  runtime/src/main/java/org/corfudb/util/MetricsUtils.java
  test/src/test/java/org/corfudb/integration/TransactionStreamIT.java
  test/src/test/java/org/corfudb/runtime/view/AddressSpaceViewTest.java
Labels: feature

#2006 High priority Clients
  infrastructure/src/main/java/org/corfudb/infrastructure/BatchProcessor.java
  infrastructure/src/main/java/org/corfudb/infrastructure/CorfuServer.java
  infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
  infrastructure/src/main/java/org/corfudb/infrastructure/ManagementServer.java
  infrastructure/src/main/java/org/corfudb/infrastructure/ResourceQuota.java
  infrastructure/src/main/java/org/corfudb/infrastructure/ServerContext.java
  infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLog.java
  infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
  infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/Orchestrator.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/ClientHandshakeHandler.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/CorfuMsg.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/ICorfuPayload.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/IMetadata.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/LogData.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/PriorityLevel.java
  runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
  runtime/src/main/java/org/corfudb/runtime/clients/AbstractClient.java
  runtime/src/main/java/org/corfudb/runtime/clients/IClient.java
  runtime/src/main/java/org/corfudb/runtime/exceptions/AbortCause.java
  runtime/src/main/java/org/corfudb/runtime/exceptions/QuotaExceededException.java
  runtime/src/main/java/org/corfudb/runtime/object/transactions/OptimisticTransactionalContext.java
  runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
  runtime/src/main/java/org/corfudb/runtime/view/ObjectsView.java
  runtime/src/main/java/org/corfudb/runtime/view/RuntimeLayout.java
  test/src/test/java/org/corfudb/infrastructure/LogUnitServerTest.java
  test/src/test/java/org/corfudb/infrastructure/ResourceQuotaTest.java
  test/src/test/java/org/corfudb/infrastructure/ServerContextBuilder.java
  test/src/test/java/org/corfudb/infrastructure/log/StreamLogFilesTest.java
  test/src/test/java/org/corfudb/integration/AbstractIT.java
  test/src/test/java/org/corfudb/integration/LogSizeQuotaIT.java
  test/src/test/java/org/corfudb/runtime/clients/LogUnitHandlerTest.java
  test/src/test/java/org/corfudb/runtime/view/replication/QuorumReplicationProtocolTest.java
Labels: 0.2.3

#2036 Prevent NPE in LocalMonitoringService
  infrastructure/src/main/java/org/corfudb/infrastructure/LocalMonitoringService.java
Labels: 0.2.3

#2048 Improved CheckpointWriter Logging
  runtime/src/main/java/org/corfudb/runtime/CheckpointWriter.java
Labels: 0.2.3, typ: enhancement

#2053 Improved CheckpointWriter Logging
  runtime/src/main/java/org/corfudb/runtime/CheckpointWriter.java
Labels: 0.2.3

#2059 Reduced The Sequencer's Memory Overhead
  infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServerCache.java
Labels: typ: enhancement

#2061 Seq mem improvement
  infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServerCache.java
Labels: 0.2.3

#2046 Do not use stale conflictKey/conflictStream on overwritten for TXNs.
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/TokenType.java
  runtime/src/main/java/org/corfudb/runtime/view/StreamsView.java
  test/src/test/java/org/corfudb/runtime/object/transactions/AbstractTransactionContextTest.java
  test/src/test/java/org/corfudb/runtime/object/transactions/OptimisticTransactionContextTest.java
Labels: typ: bug fix

#2068 Fix string formatting: correctly escape percent sign.
  infrastructure/src/main/java/org/corfudb/infrastructure/CorfuServer.java
  infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
Labels: typ: bug fix

#2076 MultiCheckpointWriter Bug Fix - 0.2.3
  runtime/src/main/java/org/corfudb/runtime/CheckpointWriter.java
  runtime/src/main/java/org/corfudb/runtime/view/stream/AddressMapStreamView.java
  test/src/test/java/org/corfudb/integration/StreamAddressDiscoveryIT.java
  test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointSmokeTest.java
Labels: 0.2.3

#2077 Add Detailed Message to IOException - 0.2.3
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/ICorfuPayload.java
  runtime/src/main/java/org/corfudb/runtime/exceptions/SerializerException.java
Labels: 0.2.3
