Repository CorfuDB/CorfuDB, pull requests merged in 2019-05, with the labels that each got.

#1837 Make the LogUnit Async
  infrastructure/src/main/java/org/corfudb/infrastructure/BatchProcessor.java
  infrastructure/src/main/java/org/corfudb/infrastructure/BatchWriter.java
  infrastructure/src/main/java/org/corfudb/infrastructure/BatchWriterOperation.java
  infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
  infrastructure/src/main/java/org/corfudb/infrastructure/ServerContext.java
  test/src/test/java/org/corfudb/infrastructure/AbstractServerTest.java
  test/src/test/java/org/corfudb/infrastructure/LogUnitServerTest.java
  test/src/test/java/org/corfudb/runtime/clients/LogUnitHandlerTest.java
Labels: typ: enhancement

#1861 Unwrap ExecutionException before re-throwing.
  runtime/src/main/java/org/corfudb/runtime/clients/NettyClientRouter.java
Labels: typ: bug fix

#1855 Revamp read/write API for better performance, stability & readibility.
  infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
  infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/ReadRequest.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/WriteMode.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/WriteRequest.java
  runtime/src/main/java/org/corfudb/recovery/FastObjectLoader.java
  runtime/src/main/java/org/corfudb/recovery/RecoveryUtils.java
  runtime/src/main/java/org/corfudb/runtime/clients/LogUnitClient.java
  runtime/src/main/java/org/corfudb/runtime/view/AbstractView.java
  runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
  runtime/src/main/java/org/corfudb/runtime/view/Layout.java
  runtime/src/main/java/org/corfudb/runtime/view/replication/AbstractReplicationProtocol.java
  runtime/src/main/java/org/corfudb/runtime/view/replication/ChainReplicationProtocol.java
  runtime/src/main/java/org/corfudb/runtime/view/replication/IReplicationProtocol.java
  runtime/src/main/java/org/corfudb/runtime/view/replication/QuorumReplicationProtocol.java
  runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractQueuedStreamView.java
  runtime/src/main/java/org/corfudb/runtime/view/stream/BackpointerStreamView.java
  test/src/test/java/org/corfudb/infrastructure/LogUnitServerTest.java
  test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java
  test/src/test/java/org/corfudb/runtime/clients/LogUnitHandlerTest.java
  test/src/test/java/org/corfudb/runtime/view/AddressSpaceViewTest.java
  test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java
  test/src/test/java/org/corfudb/runtime/view/replication/QuorumReplicationProtocolAdditionalTests.java
Labels: 2.3.0, typ: bug fix, typ: performance, typ: refactoring

#1881 Serializer: get rid of Runtime dependency on ILogData::getPayload.
  runtime/src/main/java/org/corfudb/protocols/logprotocol/CheckpointEntry.java
  runtime/src/main/java/org/corfudb/protocols/logprotocol/LogEntry.java
  runtime/src/main/java/org/corfudb/protocols/logprotocol/MultiObjectSMREntry.java
  runtime/src/main/java/org/corfudb/protocols/logprotocol/MultiSMREntry.java
  runtime/src/main/java/org/corfudb/protocols/logprotocol/SMREntry.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/ExceptionMsg.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/ILogData.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/LogData.java
  runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java
  runtime/src/main/java/org/corfudb/runtime/object/StreamViewSMRAdapter.java
  runtime/src/main/java/org/corfudb/runtime/object/transactions/OptimisticTransactionalContext.java
  runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractContextStreamView.java
  runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractQueuedStreamView.java
  runtime/src/main/java/org/corfudb/util/serializer/CorfuSerializer.java
  runtime/src/main/java/org/corfudb/util/serializer/ISerializer.java
  runtime/src/main/java/org/corfudb/util/serializer/JavaSerializer.java
  runtime/src/main/java/org/corfudb/util/serializer/JsonSerializer.java
  runtime/src/main/java/org/corfudb/util/serializer/PrimitiveSerializer.java
  runtime/src/main/java/org/corfudb/util/serializer/Serializers.java
  test/src/test/java/org/corfudb/CustomSerializer.java
  test/src/test/java/org/corfudb/infrastructure/log/StreamLogFilesTest.java
  test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java
  test/src/test/java/org/corfudb/integration/CmdletIT.java
  test/src/test/java/org/corfudb/runtime/checkpoint/CPSerializer.java
  test/src/test/java/org/corfudb/runtime/clients/LogUnitHandlerTest.java
  test/src/test/java/org/corfudb/runtime/view/AddressSpaceViewTest.java
  test/src/test/java/org/corfudb/runtime/view/ChainReplicationViewTest.java
  test/src/test/java/org/corfudb/runtime/view/LayoutViewTest.java
  test/src/test/java/org/corfudb/runtime/view/StreamViewTest.java
  test/src/test/java/org/corfudb/runtime/view/replication/AbstractReplicationProtocolTest.java
  test/src/test/java/org/corfudb/runtime/view/replication/ChainReplicationProtocolTest.java
  test/src/test/java/org/corfudb/runtime/view/replication/QuorumReplicationProtocolAdditionalTests.java
  test/src/test/java/org/corfudb/runtime/view/stream/BackpointerStreamViewTest.java
Labels: defect

#1891 Fix CI Failures for Master
  .travis.yml
Labels: bug
