Repository CorfuDB/CorfuDB, pull requests merged in 2019-03, with the labels that each got.

#1728 Fix partial bootstraps during AddNode.
  infrastructure/src/main/java/org/corfudb/infrastructure/LocalMonitoringService.java
  infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/workflows/AddNodeWorkflow.java
  runtime/src/main/java/org/corfudb/runtime/view/LayoutManagementView.java
  runtime/src/main/java/org/corfudb/runtime/view/LayoutView.java
  runtime/src/main/java/org/corfudb/runtime/view/ManagementView.java
  runtime/src/main/java/org/corfudb/util/CFUtils.java
  test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java
Labels: bug

#1626 Simplify shutdown checks in AbstractServer
  infrastructure/src/main/java/org/corfudb/infrastructure/AbstractServer.java
  infrastructure/src/main/java/org/corfudb/infrastructure/CorfuMsgHandler.java
  infrastructure/src/test/java/org/corfudb/infrastructure/CorfuAbstractServerTest.java
  test/pom.xml
  test/src/test/java/org/corfudb/runtime/view/replication/QuorumReplicationProtocolAdditionalTests.java
Labels: risk: low, typ: enhancement

#1623 Add Management Server Configuration
  infrastructure/src/main/java/org/corfudb/infrastructure/ManagementServer.java
  infrastructure/src/main/java/org/corfudb/infrastructure/ServerContext.java
  runtime/src/main/java/org/corfudb/runtime/view/IReconfigurationHandlerPolicy.java
  runtime/src/main/java/org/corfudb/runtime/view/PurgeFailurePolicy.java
  runtime/src/main/java/org/corfudb/runtime/view/SequencerHealingPolicy.java
  test/src/test/java/org/corfudb/infrastructure/ReconfigurationEventHandlerTest.java
Labels: risk: low, typ: enhancement

#1762 Make Netty keep alive message ignore epoch, fix Future handling in NettyClientRouter
  infrastructure/src/main/java/org/corfudb/infrastructure/BaseServer.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/CorfuMsgType.java
  runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
  runtime/src/main/java/org/corfudb/runtime/clients/BaseClient.java
  runtime/src/main/java/org/corfudb/runtime/clients/NettyClientRouter.java
Labels: bug

#1718 Stabilize and cleanup VM harness integration, enable cluster status check
  it/src/main/java/org/corfudb/universe/group/cluster/AbstractCorfuCluster.java
  it/src/main/java/org/corfudb/universe/group/cluster/vm/RemoteOperationHelper.java
  it/src/main/java/org/corfudb/universe/node/server/vm/VmCorfuServer.java
  it/src/test/java/org/corfudb/universe/scenario/AllNodesPartitionedIT.java
  it/src/test/java/org/corfudb/universe/scenario/ClusterResizeIT.java
  it/src/test/java/org/corfudb/universe/scenario/HandOfGodIT.java
  it/src/test/java/org/corfudb/universe/scenario/NodeDownAndLinkFailureIT.java
  it/src/test/java/org/corfudb/universe/scenario/NodeDownAndPartitionedIT.java
  it/src/test/java/org/corfudb/universe/scenario/NodePausedAndPartitionedIT.java
  it/src/test/java/org/corfudb/universe/scenario/NodeUpAndPartitionedIT.java
  it/src/test/java/org/corfudb/universe/scenario/OneLinkFailureIT.java
  it/src/test/java/org/corfudb/universe/scenario/OneNodeDownIT.java
  it/src/test/java/org/corfudb/universe/scenario/OneNodePausedIT.java
  it/src/test/java/org/corfudb/universe/scenario/RotateLinkFailureIT.java
  it/src/test/java/org/corfudb/universe/scenario/ScenarioUtils.java
  it/src/test/java/org/corfudb/universe/scenario/TwoLinksFailureIT.java
  it/src/test/java/org/corfudb/universe/scenario/TwoNodesDownIT.java
Labels: defect

#1781 Use server executor in TestServerRouter
  test/src/test/java/org/corfudb/infrastructure/BaseServerTest.java
  test/src/test/java/org/corfudb/infrastructure/TestServerRouter.java
  test/src/test/java/org/corfudb/runtime/clients/TestClientRouter.java
Labels: bug

#1700 Fix a correcness issue with bulkWrite
  infrastructure/src/main/java/org/corfudb/infrastructure/BatchWriter.java
  infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
  infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
  it/src/main/java/org/corfudb/universe/node/client/CorfuClient.java
  it/src/main/java/org/corfudb/universe/node/client/LocalCorfuClient.java
  it/src/test/java/org/corfudb/universe/scenario/ClusterResizeIT.java
  runtime/src/main/java/org/corfudb/runtime/exceptions/LogUnitException.java
  test/src/test/java/org/corfudb/infrastructure/log/StreamLogFilesTest.java
  test/src/test/java/org/corfudb/runtime/clients/LogUnitHandlerTest.java
Labels: bug

#1784 Skip bootstrapping an already bootstrapped sequencer
  infrastructure/src/main/java/org/corfudb/infrastructure/RemoteMonitoringService.java
Labels: typ: bug fix

#1789 Prevent netty channel leak
  infrastructure/src/main/java/org/corfudb/infrastructure/management/FailureDetector.java
  runtime/src/main/java/org/corfudb/runtime/BootstrapUtil.java
  runtime/src/main/java/org/corfudb/runtime/clients/NettyClientRouter.java
  runtime/src/main/java/org/corfudb/runtime/view/LayoutView.java
  runtime/src/main/java/org/corfudb/runtime/view/ManagementView.java
  runtime/src/main/java/org/corfudb/runtime/view/SealServersHelper.java
  test/src/test/java/org/corfudb/integration/AbstractIT.java
  test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java
  test/src/test/java/org/corfudb/integration/CmdletIT.java
  test/src/test/java/org/corfudb/integration/CorfuMsgFilterIT.java
  test/src/test/java/org/corfudb/integration/Harness.java
  test/src/test/java/org/corfudb/integration/LargeWriteIT.java
  test/src/test/java/org/corfudb/integration/MemoryFootprintIT.java
  test/src/test/java/org/corfudb/integration/SealIT.java
  test/src/test/java/org/corfudb/integration/SecurityIT.java
  test/src/test/java/org/corfudb/integration/ServerRestartIT.java
  test/src/test/java/org/corfudb/integration/WorkflowIT.java
Labels: typ: bug fix

#1797 Check nested transaction type mismatch upon txn begin
  runtime/src/main/java/org/corfudb/runtime/object/transactions/Transaction.java
  test/src/test/java/org/corfudb/runtime/object/transactions/OptimisticTransactionContextTest.java
Labels: typ: bug fix

#1771 Allow transactions that span epochs to commit if primary sequencer does not change.
  infrastructure/src/main/java/org/corfudb/infrastructure/CorfuServer.java
  infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java
  infrastructure/src/main/java/org/corfudb/infrastructure/ServerContext.java
  test/src/test/java/org/corfudb/infrastructure/SequencerServerAssertions.java
  test/src/test/java/org/corfudb/infrastructure/SequencerServerTest.java
  test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java
  test/src/test/java/org/corfudb/runtime/object/transactions/AbstractTransactionsTest.java
  test/src/test/java/org/corfudb/runtime/object/transactions/OptimisticTransactionContextTest.java
  test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java
Labels: typ: performance

#1622 Sequencer server config
  infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java
  infrastructure/src/main/java/org/corfudb/infrastructure/ServerContext.java
  runtime/src/main/java/org/corfudb/runtime/view/Address.java
Labels: risk: low, typ: enhancement
