Repository CorfuDB/CorfuDB, pull requests merged in 2020-08, with the labels that each got.

#2712 Fail Non-Transactional Enqueue
  runtime/src/main/java/org/corfudb/runtime/collections/CorfuQueue.java
  test/src/test/java/org/corfudb/runtime/collections/CorfuQueueTest.java
Labels: bug

#2699 Remove Java Generics From CorfuQueue's API
  runtime/src/main/java/org/corfudb/protocols/logprotocol/SMREntry.java
  runtime/src/main/java/org/corfudb/runtime/collections/CorfuQueue.java
  runtime/src/main/java/org/corfudb/util/serializer/CorfuQueueSerializer.java
  runtime/src/main/java/org/corfudb/util/serializer/Serializers.java
  test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointTest.java
  test/src/test/java/org/corfudb/runtime/collections/CorfuQueueTest.java
  test/src/test/java/org/corfudb/runtime/concurrent/CorfuQueueTxTest.java
Labels: typ: enhancement

#2661 File descriptor leaks corfu 0.3.0.2
  checks.xml
  infrastructure/src/main/java/org/corfudb/infrastructure/BatchProcessor.java
  infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
  infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogCompaction.java
  infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
  it/src/test/java/org/corfudb/universe/scenario/BaseServerFileDescriptorLeaksIT.java
  it/src/test/java/org/corfudb/universe/spec/FileDescriptorLeaksSpec.java
  runtime/src/main/java/org/corfudb/runtime/view/stream/StreamAddressSpace.java
  test/src/main/java/org/corfudb/test/LsofSpec.java
  test/src/test/java/org/corfudb/AbstractCorfuTest.java
  test/src/test/java/org/corfudb/infrastructure/log/StreamLogCompactionTest.java
  test/src/test/java/org/corfudb/infrastructure/log/StreamLogFilesTest.java
  test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java
Labels: 0.3.0

#2715 Sequencer Reconfiguration Corruption Fixes
  infrastructure/src/main/java/org/corfudb/infrastructure/BatchProcessor.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/StreamsAddressResponse.java
  runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
  runtime/src/main/java/org/corfudb/runtime/view/Layout.java
  runtime/src/main/java/org/corfudb/runtime/view/LayoutManagementView.java
  runtime/src/main/java/org/corfudb/runtime/view/StreamsView.java
  runtime/src/main/java/org/corfudb/runtime/view/stream/StreamAddressSpace.java
  runtime/src/main/java/org/corfudb/util/Utils.java
  test/src/test/java/org/corfudb/infrastructure/LogUnitServerTest.java
  test/src/test/java/org/corfudb/infrastructure/logreplication/LogUpdateAPITest.java
  test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java
  test/src/test/java/org/corfudb/integration/LogReplicationIT.java
  test/src/test/java/org/corfudb/integration/ServerRestartIT.java
  test/src/test/java/org/corfudb/integration/StreamAddressDiscoveryIT.java
  test/src/test/java/org/corfudb/runtime/utils/UtilsTest.java
  test/src/test/java/org/corfudb/runtime/view/AddressSpaceViewTest.java
  test/src/test/java/org/corfudb/runtime/view/stream/StreamAddressSpaceTest.java
Labels: bug

#2724 [Corfu- 0.3.0.2] Write path optimization
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/DataType.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/ILogData.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/IMetadata.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/LogData.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/LogData.java.rej
  runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
  runtime/src/main/java/org/corfudb/runtime/view/StreamsView.java
  runtime/src/main/java/org/corfudb/runtime/view/replication/ChainReplicationProtocol.java
  runtime/src/main/java/org/corfudb/runtime/view/replication/QuorumReplicationProtocol.java
  runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractQueuedStreamView.java
  test/src/test/java/org/corfudb/runtime/clients/LogUnitHandlerTest.java
Labels: 0.3.0

#2703 Stream write path performance optimization.
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/DataType.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/ILogData.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/IMetadata.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/LogData.java
  runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
  runtime/src/main/java/org/corfudb/runtime/view/StreamsView.java
  runtime/src/main/java/org/corfudb/runtime/view/replication/ChainReplicationProtocol.java
  runtime/src/main/java/org/corfudb/runtime/view/replication/QuorumReplicationProtocol.java
  runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractQueuedStreamView.java
  test/src/test/java/org/corfudb/runtime/clients/LogUnitHandlerTest.java
Labels: typ: performance

#2735 Fix auto commit range check and flaky unit test.
  infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogDataStore.java
  runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
  test/src/test/java/org/corfudb/infrastructure/AutoCommitServiceTest.java
Labels: bug

#2736 Reset SinkBufferManager on negotiation
  infrastructure/src/main/java/org/corfudb/infrastructure/LogReplicationServer.java
  infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationMetadataManager.java
  runtime/src/main/java/org/corfudb/util/Utils.java
Labels: bug, log-replication
