Repository CorfuDB/CorfuDB, pull requests merged in 2020-01, with the labels that each got.

#2266 Decouple UT From Server Executors
  infrastructure/src/main/java/org/corfudb/infrastructure/BatchProcessor.java
  infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
  runtime/src/main/java/org/corfudb/runtime/clients/ClientMsgHandler.java
  test/src/test/java/org/corfudb/infrastructure/AbstractServerTest.java
  test/src/test/java/org/corfudb/infrastructure/BaseServerTest.java
  test/src/test/java/org/corfudb/infrastructure/CorfuServerNodeTest.java
  test/src/test/java/org/corfudb/infrastructure/LayoutServerTest.java
  test/src/test/java/org/corfudb/infrastructure/LogUnitCacheTest.java
  test/src/test/java/org/corfudb/infrastructure/LogUnitServerTest.java
  test/src/test/java/org/corfudb/infrastructure/ManagementServerTest.java
  test/src/test/java/org/corfudb/infrastructure/SequencerServerTest.java
  test/src/test/java/org/corfudb/infrastructure/TestServerRouter.java
  test/src/test/java/org/corfudb/runtime/clients/LogUnitHandlerTest.java
  test/src/test/java/org/corfudb/runtime/clients/ManagementHandlerTest.java
  test/src/test/java/org/corfudb/runtime/object/transactions/SequencerServerCacheTest.java
  test/src/test/java/org/corfudb/runtime/view/AbstractViewTest.java
  test/src/test/java/org/corfudb/runtime/view/LayoutSealTest.java
  test/src/test/java/org/corfudb/runtime/view/LogUnitSealTest.java
Labels: typ: enhancement

#2305 Remove heart beat counter
  infrastructure/src/main/java/org/corfudb/infrastructure/ManagementServer.java
  infrastructure/src/main/java/org/corfudb/infrastructure/management/ClusterStateCollector.java
  infrastructure/src/main/java/org/corfudb/infrastructure/management/ClusterStateContext.java
  infrastructure/src/main/java/org/corfudb/infrastructure/management/FailureDetector.java
  infrastructure/src/test/java/org/corfudb/infrastructure/management/ClusterGraphTest.java
  infrastructure/src/test/java/org/corfudb/infrastructure/management/ClusterStateAggregatorTest.java
  infrastructure/src/test/java/org/corfudb/infrastructure/management/ClusterStateCollectorTest.java
  infrastructure/src/test/java/org/corfudb/infrastructure/management/ClusterStateTest.java
  infrastructure/src/test/java/org/corfudb/infrastructure/management/FailureDetectorTest.java
  infrastructure/src/test/java/org/corfudb/infrastructure/management/NodeStateTestUtil.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/NodeState.java
  runtime/src/test/java/org/corfudb/protocols/wireprotocol/NodeStateTest.java
Labels: typ: enhancement

#2272 Improved Thread Management
  infrastructure/src/main/java/org/corfudb/infrastructure/AbstractServer.java
  infrastructure/src/main/java/org/corfudb/infrastructure/BaseServer.java
  infrastructure/src/main/java/org/corfudb/infrastructure/HandlerMethods.java
  infrastructure/src/main/java/org/corfudb/infrastructure/LayoutServer.java
  infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
  infrastructure/src/main/java/org/corfudb/infrastructure/ManagementServer.java
  infrastructure/src/main/java/org/corfudb/infrastructure/NettyServerRouter.java
  infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java
  infrastructure/src/test/java/org/corfudb/infrastructure/CorfuAbstractServerTest.java
  runtime/src/main/java/org/corfudb/runtime/clients/ClientMsgHandler.java
  test/src/test/java/org/corfudb/infrastructure/SequencerServerTest.java
  test/src/test/java/org/corfudb/infrastructure/TestServerRouter.java
  test/src/test/java/org/corfudb/runtime/clients/SequencerHandlerTest.java
Labels: typ: enhancement

#2308 End-to-end compression: remove compressed flag and related checks.
  infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/IMetadata.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/LogData.java
Labels: typ: refactoring

#2267 Remove Heart Beat Executor
  infrastructure/src/main/java/org/corfudb/infrastructure/AbstractServer.java
  infrastructure/src/main/java/org/corfudb/infrastructure/BaseServer.java
  infrastructure/src/main/java/org/corfudb/infrastructure/LayoutServer.java
  infrastructure/src/main/java/org/corfudb/infrastructure/ManagementServer.java
  infrastructure/src/test/java/org/corfudb/infrastructure/CorfuAbstractServerTest.java
  test/src/test/java/org/corfudb/infrastructure/ManagementServerTest.java
Labels: typ: enhancement

#2317 PersistedStreamingMap SIGSEGV Fix
  runtime/src/main/java/org/corfudb/runtime/collections/PersistedStreamingMap.java
  runtime/src/main/java/org/corfudb/runtime/collections/RocksDbEntryIterator.java
  runtime/src/main/java/org/corfudb/runtime/collections/WrappedRocksIterator.java
  runtime/src/main/java/org/corfudb/runtime/view/TableRegistry.java
  test/src/test/java/org/corfudb/infrastructure/log/StreamLogFilesTest.java
  test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointTest.java
  test/src/test/java/org/corfudb/runtime/collections/RocksDbEntryIteratorTest.java
Labels: bug, typ: bug fix

#2325 VersionLockedObject and CorfuTable Deadlock
  runtime/src/main/java/org/corfudb/runtime/collections/CorfuTable.java
Labels: bug
