Repository CorfuDB/CorfuDB, pull requests merged in 2021-01, with the labels that each got.

#2850 Fix NPE thrown by browser tool when value and/or metadata are null.
  corfudb-tools/src/main/java/org/corfudb/browser/CorfuStoreBrowser.java
  test/src/test/java/org/corfudb/integration/CorfuStoreBrowserIT.java
Labels: bug, priority: medium

#2737 Added Doxyfile
  .gitignore
  Doxyfile
  README.md
Labels: typ: enhancement

#2855 Remove QuorumReplicationProtocol
  infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
  infrastructure/src/main/java/org/corfudb/infrastructure/log/InMemoryStreamLog.java
  infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
  infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogWithRankedAddressSpace.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/CorfuMsgType.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/ICorfuPayload.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/IMetadata.java
  runtime/src/main/java/org/corfudb/runtime/clients/LogUnitClient.java
  runtime/src/main/java/org/corfudb/runtime/clients/LogUnitHandler.java
  runtime/src/main/java/org/corfudb/runtime/exceptions/DataOutrankedException.java
  runtime/src/main/java/org/corfudb/runtime/exceptions/ValueAdoptedException.java
  runtime/src/main/java/org/corfudb/runtime/view/Layout.java
  runtime/src/main/java/org/corfudb/runtime/view/replication/QuorumReplicationProtocol.java
  runtime/src/test/java/org/corfudb/protocols/wireprotocol/ICorfuPayloadTest.java
  test/src/test/java/org/corfudb/infrastructure/LayoutBuilderTest.java
  test/src/test/java/org/corfudb/infrastructure/LogUnitServerTest.java
  test/src/test/java/org/corfudb/infrastructure/log/StreamLogWithRankedAddressSpaceTest.java
  test/src/test/java/org/corfudb/runtime/clients/LogUnitHandlerTest.java
  test/src/test/java/org/corfudb/runtime/view/LayoutManagementViewTest.java
  test/src/test/java/org/corfudb/runtime/view/LayoutSealTest.java
  test/src/test/java/org/corfudb/runtime/view/QuorumReplicationStreamViewTest.java
  test/src/test/java/org/corfudb/runtime/view/replication/QuorumReplicationProtocolAdditionalTests.java
  test/src/test/java/org/corfudb/runtime/view/replication/QuorumReplicationProtocolTest.java
Labels: typ: enhancement

#2826 CorfuStore streaming redesign part 3 - implementation and integration.
  runtime/proto/example_schemas.proto
  runtime/src/main/java/org/corfudb/runtime/collections/CorfuStore.java
  runtime/src/main/java/org/corfudb/runtime/collections/CorfuStoreShim.java
  runtime/src/main/java/org/corfudb/runtime/collections/CorfuStreamEntry.java
  runtime/src/main/java/org/corfudb/runtime/collections/StreamListener.java
  runtime/src/main/java/org/corfudb/runtime/collections/StreamManager.java
  runtime/src/main/java/org/corfudb/runtime/collections/StreamNotificationTask.java
  runtime/src/main/java/org/corfudb/runtime/collections/StreamPollingTask.java
  runtime/src/main/java/org/corfudb/runtime/collections/StreamSubscription.java
  runtime/src/main/java/org/corfudb/runtime/collections/StreamSubscriptionMetrics.java
  runtime/src/main/java/org/corfudb/runtime/collections/StreamingManager.java
  runtime/src/main/java/org/corfudb/runtime/collections/Table.java
  runtime/src/main/java/org/corfudb/runtime/view/SequencerView.java
  runtime/src/main/java/org/corfudb/runtime/view/StreamOptions.java
  runtime/src/main/java/org/corfudb/runtime/view/TableRegistry.java
  runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractContextStreamView.java
  runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractQueuedStreamView.java
  runtime/src/main/java/org/corfudb/runtime/view/stream/AddressMapStreamView.java
  runtime/src/main/java/org/corfudb/runtime/view/stream/BackpointerStreamView.java
  runtime/src/main/java/org/corfudb/runtime/view/stream/IStreamView.java
  runtime/src/main/java/org/corfudb/runtime/view/stream/ThreadSafeStreamView.java
  test/src/test/java/org/corfudb/integration/StreamingIT.java
  test/src/test/java/org/corfudb/runtime/collections/CorfuStoreTest.java
  test/src/test/resources/proto/sample_schema.proto
Labels: feature, typ: performance

#2864 Remove drop wizard
  cmdlets/src/main/java/org/corfudb/metrics/MBeanDumperApp.java
  cmdlets/src/main/java/org/corfudb/metrics/MBeanUtils.java
  common/pom.xml
  common/src/main/java/org/corfudb/common/metrics/MetricsServer.java
  common/src/main/java/org/corfudb/common/metrics/servers/PrometheusMetricsServer.java
  common/src/main/java/org/corfudb/common/util/Memory.java
  infrastructure/src/main/java/org/corfudb/infrastructure/CorfuServer.java
  infrastructure/src/main/java/org/corfudb/infrastructure/HandlerMethods.java
  infrastructure/src/main/java/org/corfudb/infrastructure/LogReplicationRuntimeParameters.java
  infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServerCache.java
  infrastructure/src/main/java/org/corfudb/infrastructure/RequestHandlerMethods.java
  infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServerCache.java
  infrastructure/src/main/java/org/corfudb/infrastructure/ServerContext.java
  infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogCompaction.java
  infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuInterClusterReplicationServer.java
  infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/logreader/StreamsSnapshotReader.java
  runtime/pom.xml
  runtime/src/main/java/org/corfudb/protocols/logprotocol/MultiObjectSMREntry.java
  runtime/src/main/java/org/corfudb/runtime/CheckpointWriter.java
  runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
  runtime/src/main/java/org/corfudb/runtime/MultiCheckpointWriter.java
  runtime/src/main/java/org/corfudb/runtime/RuntimeParameters.java
  runtime/src/main/java/org/corfudb/runtime/RuntimeParametersBuilder.java
  runtime/src/main/java/org/corfudb/runtime/clients/LogUnitClient.java
  runtime/src/main/java/org/corfudb/runtime/clients/NettyClientRouter.java
  runtime/src/main/java/org/corfudb/runtime/collections/Table.java
  runtime/src/main/java/org/corfudb/runtime/collections/TableMetrics.java
  runtime/src/main/java/org/corfudb/runtime/collections/TimingHistogram.java
  runtime/src/main/java/org/corfudb/runtime/collections/TxnContext.java
  runtime/src/main/java/org/corfudb/runtime/object/transactions/AbstractTransactionalContext.java
  runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
  runtime/src/main/java/org/corfudb/runtime/view/ObjectsView.java
  runtime/src/main/java/org/corfudb/util/CorfuComponent.java
  runtime/src/main/java/org/corfudb/util/MetricsUtils.java
  scripts/metrics_dumper.sh
  test/src/test/java/org/corfudb/common/metrics/servers/PrometheusMetricsServerTest.java
  test/src/test/java/org/corfudb/infrastructure/log/StreamLogCompactionTest.java
  test/src/test/java/org/corfudb/runtime/clients/ManagementHandlerTest.java
  test/src/test/java/org/corfudb/runtime/clients/SequencerHandlerTest.java
  test/src/test/java/org/corfudb/runtime/collections/CorfuStoreShimTest.java
  test/src/test/java/org/corfudb/runtime/view/AddressSpaceViewTest.java
  test/src/test/java/org/corfudb/util/MemoryFootprintMeasurerIT.java
Labels: bug
