Repository CorfuDB/CorfuDB, pull requests merged in 2021-02, with the labels that each got.

#2866 Hide Stream Bitmap Implementation
  infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java
  infrastructure/src/main/java/org/corfudb/infrastructure/log/LogMetadata.java
  infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/LogReplicationAckReader.java
  infrastructure/src/test/java/org/corfudb/infrastructure/LogUnitServerTest.java
  infrastructure/src/test/java/org/corfudb/infrastructure/SequencerServerTest.java
  runtime/proto/rpc_common.proto
  runtime/src/main/java/org/corfudb/protocols/CorfuProtocolCommon.java
  runtime/src/main/java/org/corfudb/protocols/wireprotocol/ICorfuPayload.java
  runtime/src/main/java/org/corfudb/runtime/view/Address.java
  runtime/src/main/java/org/corfudb/runtime/view/stream/AddressMapStreamView.java
  runtime/src/main/java/org/corfudb/runtime/view/stream/StreamAddressSpace.java
  test/src/test/java/org/corfudb/infrastructure/LogUnitServerTest.java
  test/src/test/java/org/corfudb/infrastructure/SequencerServerTest.java
  test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java
  test/src/test/java/org/corfudb/integration/ServerRestartIT.java
  test/src/test/java/org/corfudb/integration/StreamAddressDiscoveryIT.java
  test/src/test/java/org/corfudb/runtime/clients/LogUnitHandlerTest.java
  test/src/test/java/org/corfudb/runtime/utils/UtilsTest.java
  test/src/test/java/org/corfudb/runtime/view/SequencerViewTest.java
  test/src/test/java/org/corfudb/runtime/view/stream/StreamAddressSpaceTest.java
Labels: bug

#2856 Log Replication: Use Node Id to communicate
  infrastructure/proto/log_replication_cluster_info.proto
  infrastructure/src/main/java/org/corfudb/infrastructure/CorfuServer.java
  infrastructure/src/main/java/org/corfudb/infrastructure/LogReplicationServer.java
  infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
  infrastructure/src/main/java/org/corfudb/infrastructure/ServerContext.java
  infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/ClusterDescriptor.java
  infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuInterClusterReplicationServer.java
  infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryService.java
  infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/NodeDescriptor.java
  infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/TopologyDescriptor.java
  infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/plugins/DefaultClusterConfig.java
  infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/plugins/DefaultClusterManager.java
  infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/LogReplicationAckReader.java
  infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/runtime/CorfuLogReplicationRuntime.java
  infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/runtime/LogReplicationClientRouter.java
  infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/runtime/fsm/LogReplicationRuntimeEvent.java
  infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/runtime/fsm/NegotiatingState.java
  infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/runtime/fsm/ReplicatingState.java
  infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/runtime/fsm/VerifyingRemoteLeaderState.java
  infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/runtime/fsm/WaitingForConnectionsState.java
  infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/transport/client/IClientChannelAdapter.java
  infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/transport/sample/CorfuNettyClientChannel.java
  infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/transport/sample/GRPCLogReplicationClientChannelAdapter.java
  infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/transport/sample/NettyLogReplicationClientChannelAdapter.java
  runtime/proto/messages.proto
  runtime/proto/service/log_replication.proto
  runtime/src/main/java/org/corfudb/protocols/service/CorfuProtocolLogReplication.java
  runtime/src/main/java/org/corfudb/util/Utils.java
  test/src/test/java/org/corfudb/integration/AbstractIT.java
  test/src/test/java/org/corfudb/integration/LogReplicationAbstractIT.java
  utils/src/main/java/org/corfudb/utils/lock/persistence/LockStore.java
Labels: log-replication

#2880 Server Parameter Parsing Fix
  common/pom.xml
  infrastructure/src/main/java/org/corfudb/infrastructure/CorfuServer.java
  infrastructure/src/main/java/org/corfudb/infrastructure/ServerContext.java
  infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuInterClusterReplicationServer.java
  test/src/test/java/org/corfudb/infrastructure/ServerContextBuilder.java
Labels: bug

#2881 Remove An Unnecessary RW Lock
  infrastructure/src/main/java/org/corfudb/infrastructure/log/MultiReadWriteLock.java
  infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
  test/src/test/java/org/corfudb/infrastructure/log/MultiReadWriteLockTest.java
  test/src/test/java/org/corfudb/infrastructure/log/StreamLogFilesTest.java
Labels: typ: enhancement

#2883 Reduce Number of Server Threads
  infrastructure/src/main/java/org/corfudb/infrastructure/CorfuServer.java
  infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuInterClusterReplicationServer.java
Labels: typ: enhancement

#2769 Local datastore read/write performance improvement.
  infrastructure/src/main/java/org/corfudb/infrastructure/datastore/DataStore.java
  test/src/test/java/org/corfudb/infrastructure/DataStoreTest.java
Labels: NFS-100, typ: performance
